apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: grafana
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-06-25T20:53:23Z"
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.0.2
    helm.sh/chart: grafana-9.2.7
  name: grafana-clusterrole
  resourceVersion: "1677695"
  uid: 7c9e4c81-119d-4b4c-8957-0e7caa341e0c
rules: null
