apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mongodb-service","namespace":"default"},"spec":{"ports":[{"port":27017,"targetPort":27017}],"selector":{"app":"mongodb"}}}
  creationTimestamp: "2025-07-19T17:38:45Z"
  name: mongodb-service
  namespace: default
  resourceVersion: "7956621"
  uid: 7831b1c7-e562-47cf-8dbd-570da7816a5a
spec:
  clusterIP: 10.110.11.75
  clusterIPs:
  - 10.110.11.75
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
