apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"deansie-wordle-backend","namespace":"default"},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"deansie-wordle-backend"}},"template":{"metadata":{"labels":{"app":"deansie-wordle-backend"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"5081"}],"image":"192.168.0.82:5000/deansie-wordle-backend:26","imagePullPolicy":"Always","name":"deansie-wordle-backend","ports":[{"containerPort":5081}],"readinessProbe":{"initialDelaySeconds":5,"periodSeconds":10,"tcpSocket":{"port":5081}},"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2025-07-19T19:06:44Z"
  generation: 6
  name: deansie-wordle-backend
  namespace: default
  resourceVersion: "13102474"
  uid: 2eb8768d-4b52-458f-b936-d132af4ffee2
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deansie-wordle-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deansie-wordle-backend
    spec:
      containers:
      - env:
        - name: PORT
          value: "5081"
        image: 192.168.0.82:5000/deansie-wordle-backend:26
        imagePullPolicy: Always
        name: deansie-wordle-backend
        ports:
        - containerPort: 5081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5081
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2025-07-29T16:07:08Z"
    lastUpdateTime: "2025-07-29T16:07:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-19T19:06:44Z"
    lastUpdateTime: "2025-08-08T09:22:57Z"
    message: ReplicaSet "deansie-wordle-backend-b74d7bb99" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
