apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"kvikkjokk-nextjs","namespace":"default"},"spec":{"replicas":4,"selector":{"matchLabels":{"app":"kvikkjokk-nextjs"}},"template":{"metadata":{"labels":{"app":"kvikkjokk-nextjs"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"server","operator":"In","values":["server1","server2"]}]},"weight":100}]},"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchLabels":{"app":"kvikkjokk-nextjs"}},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"env":[{"name":"PORT","value":"9001"},{"name":"MONGODB_URI","valueFrom":{"secretKeyRef":{"key":"mongodb-uri","name":"kvikkjokk-nextjs-secrets"}}},{"name":"OMDB_API_KEY","valueFrom":{"secretKeyRef":{"key":"omdb-api-key","name":"kvikkjokk-nextjs-secrets"}}},{"name":"DEEPL_API_KEY","valueFrom":{"secretKeyRef":{"key":"deepl-api-key","name":"kvikkjokk-nextjs-secrets"}}}],"image":"192.168.0.82:5000/kvikkjokk-nextjs:5","imagePullPolicy":"Always","name":"kvikkjokk-nextjs","ports":[{"containerPort":9001}],"readinessProbe":{"httpGet":{"path":"/","port":9001},"initialDelaySeconds":5,"periodSeconds":10},"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2025-06-19T11:06:59Z"
  generation: 8
  name: kvikkjokk-nextjs
  namespace: default
  resourceVersion: "10563140"
  uid: 378683a6-752f-4635-b9cc-10934548b7cd
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kvikkjokk-nextjs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kvikkjokk-nextjs
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: server
                operator: In
                values:
                - server1
                - server2
            weight: 100
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: kvikkjokk-nextjs
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: PORT
          value: "9001"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongodb-uri
              name: kvikkjokk-nextjs-secrets
        - name: OMDB_API_KEY
          valueFrom:
            secretKeyRef:
              key: omdb-api-key
              name: kvikkjokk-nextjs-secrets
        - name: DEEPL_API_KEY
          valueFrom:
            secretKeyRef:
              key: deepl-api-key
              name: kvikkjokk-nextjs-secrets
        image: 192.168.0.82:5000/kvikkjokk-nextjs:5
        imagePullPolicy: Always
        name: kvikkjokk-nextjs
        ports:
        - containerPort: 9001
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2025-06-25T17:32:32Z"
    lastUpdateTime: "2025-07-16T11:43:25Z"
    message: ReplicaSet "kvikkjokk-nextjs-684b758d99" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-29T16:07:51Z"
    lastUpdateTime: "2025-07-29T16:07:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
